### ISSUE TITLE
ElasticBeanstalk ApplicationVersion is incomplete

### ISSUE THREAD

**Issue by mweagle** [crewjam/go-cloudformation#13]
Hi Russ,
In adding an [ElasticBeanstalkApplicationVersion](https://github.com/crewjam/go-cloudformation/blob/master/schema.go#L2774) ref, it seems like the codegen didn't pickup the associated [properties](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-version.html).  

What's the best way for me to address & verify s.t. I can submit a PR?  Thanks.

**Comment by crewjam** [comment]
Looks like the heading there is "Members" vs "Properties" or "Parameters" which are more common. The fix is probably around https://github.com/crewjam/go-cloudformation/blob/master/scraper/scrape.go#L218

Then, it's just `go generate .`

If you've run go generate before you'll need to nuke your .scraper-cache

**Comment by mweagle** [comment]
Thanks Ross - I'll work up a PR in the next couple of days.  After a bit more work it turns out EB is a bad fit altogether.  Now descending into the depths of EC2 CloudInit scripts.

**Comment by mweagle** [comment]
Haven't forgotten about this, but I've been in a dark EC2 CloudInit place fighting CI systems. Will have a PR once I'm out.  Cheers.
